INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿布哈兹', '阿布哈兹自治共和国', 'Abkhazia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿富汗', '阿富汗伊斯兰共和国', 'Afghanistan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿尔巴尼亚', '阿尔巴尼亚共和国', 'Albania');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿尔及利亚', '阿尔及利亚人民民主共和国', 'Algeria');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '美属萨摩亚（美国）', '美属萨摩亚', 'American Samoa');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '安道尔', '安道尔公国', 'Andorra');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '安哥拉', '安哥拉共和国', 'Angola');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '安圭拉 (英国)', '安圭拉', 'Anguilla');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '安提瓜和巴布达', '安提瓜和巴布达', 'Antigua and Barbuda');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿根廷', '阿根廷共和国', 'Argentina');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '亚美尼亚', '亚美尼亚共和国', 'Armenia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿鲁巴（荷兰）', '阿鲁巴', 'Aruba');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '澳大利亚', '澳大利亚联邦', 'Australia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '奥地利', '奥地利共和国', 'Austria');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿塞拜疆', '阿塞拜疆共和国', 'Azerbaijan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴哈马', '巴哈马国', 'Bahamas, The');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴林', '巴林王国', 'Bahrain');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '孟加拉国', '孟加拉人民共和国', 'Bangladesh');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴巴多斯', '巴巴多斯', 'Barbados');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '白俄罗斯', '白俄罗斯共和国', 'Belarus');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '比利时', '比利时王国', 'Belgium');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '伯利兹', '伯利兹', 'Belize');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '贝宁', '贝宁共和国', 'Benin');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '百慕大（英国）', '百慕大', 'Bermuda');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '不丹', '不丹王国', 'Bhutan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '玻利维亚', '多民族玻利维亚国', 'Bolivia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '波黑', '波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '博茨瓦纳', '博茨瓦纳共和国', 'Botswana');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴西', '巴西联邦共和国', 'Brazil');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '英属印度洋领地（英国）', '英属印度洋领地', 'British Indian Ocean Territory');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '文莱', '文莱达鲁萨兰国', 'Brunei');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '保加利亚', '保加利亚共和国', 'Bulgaria');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '布基纳法索', '布基纳法索', 'Burkina Faso');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '布隆迪', '布隆迪共和国', 'Burundi');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '柬埔寨', '柬埔寨王国', 'Cambodia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '喀麦隆', '喀麦隆共和国', 'Cameroon');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '加拿大', '加拿大', 'Canada');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '佛得角', '佛得角共和国', 'Cape Verde');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '开曼群岛（英国）', '开曼群岛', 'Cayman Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '中非共和国', '中非共和国', 'Central African Republic');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '乍得', '乍得共和国', 'Chad');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '智利', '智利共和国', 'Chile');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '中国', '中华人民共和国', 'China');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣诞岛（澳大利亚）', '圣诞岛', 'Christmas lsland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '科科斯(基林)群岛（澳大利亚）', '科科斯（基林）群岛', 'Cocos (Keeling) Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '哥伦比亚', '哥伦比亚共和国', 'Colombia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '科摩罗', '科摩罗联盟', 'Comoros');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '刚果共和国', '刚果共和国', 'Congo (Brazzaville)');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '刚果民主共和国', '刚果民主共和国', 'Congo (Kinshasa)');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '库克群岛（新西兰）', '库克群岛', 'Cook Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '哥斯达黎加', '哥斯达黎加共和国', 'Costa Rica');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '科特迪瓦', '科特迪瓦共和国', 'Côte dIvoire');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '克罗地亚', '克罗地亚共和国', 'Croatia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '古巴', '古巴共和国', 'Cuba');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '库拉索(荷兰)', '库拉索', 'Curaçao');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塞浦路斯', '塞浦路斯共和国', 'Cyprus');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '捷克', '捷克共和国', 'Czech Republic');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '丹麦', '丹麦王国', 'Denmark');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '吉布提', '吉布提共和国', 'Djibouti');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '多米尼克', '多米尼克国', 'Dominica');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '多米尼加', '多米尼加共和国', 'Dominican Republic');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '厄瓜多尔', '厄瓜多尔共和国', 'Ecuador');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '埃及', '阿拉伯埃及共和国', 'Egypt');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '萨尔瓦多', '萨尔瓦多共和国', 'El Salvador');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '赤道几内亚', '赤道几内亚共和国', 'Equatorial Guinea');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '厄立特里亚', '厄立特里亚国', 'Eritrea');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '爱沙尼亚', '爱沙尼亚共和国', 'Estonia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '埃塞俄比亚', '埃塞俄比亚联邦民主共和国', 'Ethiopia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '福克兰群岛（英国、阿根廷争议）', '福克兰群岛（马尔维纳斯群岛）', 'Falkland Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '法罗群岛（丹麦）', '法罗群岛', 'Faroe Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斐济', '斐济共和国', 'Fiji');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '芬兰', '芬兰共和国', 'Finland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '法国', '法兰西共和国', 'France');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '法属波利尼西亚（法国）', '法属波利尼西亚', 'French Polynesia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '加蓬', '加蓬共和国', 'Gabon');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '冈比亚', '冈比亚共和国', 'Gambia, The');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '格鲁吉亚', '格鲁吉亚', 'Georgia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '德国', '德意志联邦共和国', 'Germany');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '加纳', '加纳共和国', 'Ghana');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '直布罗陀（英国）', '直布罗陀', 'Gibraltar');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '希腊', '希腊共和国', 'Greece');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '格陵兰（丹麦）', '格陵兰', 'Greenland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '格林纳达', '格林纳达', 'Grenada');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '关岛（美国）', '关岛', 'Guam');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '危地马拉', '危地马拉共和国', 'Guatemala');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '根西岛（英国）', '根西岛', 'Guernsey');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '几内亚', '几内亚共和国', 'Guinea');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '几内亚比绍', '几内亚比绍共和国', 'Guinea-Bissau');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圭亚那', '圭亚那合作共和国', 'Guyana');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '海地', '海地共和国', 'Haiti');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '洪都拉斯', '洪都拉斯共和国', 'Honduras');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '中国香港', '中华人民共和国香港特别行政区', 'Hong Kong');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '匈牙利', '匈牙利', 'Hungary');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '冰岛', '冰岛共和国', 'Iceland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '印度', '印度共和国', 'India');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '印尼', '印度尼西亚共和国', 'Indonesia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '伊朗', '伊朗伊斯兰共和国', 'Iran');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '伊拉克', '伊拉克共和国', 'Iraq');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '爱尔兰', '爱尔兰共和国', 'Ireland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '以色列', '以色列国', 'Israel');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '意大利', '意大利共和国', 'Italy');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '牙买加', '牙买加', 'Jamaica');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '日本', '日本国', 'Japan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '泽西岛（英国）', '泽西岛', 'Jersey');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '约旦', '约旦哈希姆王国', 'Jordan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( ' 哈萨克斯坦', '哈萨克斯坦共和国', 'Kazakhstan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '肯尼亚', '肯尼亚共和国', 'Kenya');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '基里巴斯', '基里巴斯共和国', 'Kiribati');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '韩国', '大韩民国', 'Korea, South');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '科索沃', '科索沃共和国', 'Kosovo');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '科威特', '科威特国', 'Kuwait');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '吉尔吉斯斯坦', '吉尔吉斯斯坦共和国', 'Kyrgyzstan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '老挝', '老挝人民民主共和国', 'Laos');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '拉脱维亚', '拉脱维亚共和国', 'Latvia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '黎巴嫩', '黎巴嫩共和国', 'Lebanon');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '莱索托', '莱索托王国', 'Lesotho');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '利比里亚', '利比里亚共和国', 'Liberia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '利比亚', '利比亚国', 'Libya');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '列支敦士登', '列支敦士登公国', 'Liechtenstein');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '立陶宛', '立陶宛共和国', 'Lithuania');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '卢森堡', '卢森堡大公国', 'Luxembourg');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '中国澳门', '中华人民共和国澳门特别行政区', 'Macao');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马其顿', '马其顿共和国', 'Macedonia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马达加斯加', '马达加斯加共和国', 'Madagascar');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马拉维', '马拉维共和国', 'Malawi');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马来西亚', '马来西亚', 'Malaysia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马尔代夫', '马尔代夫共和国', 'Maldives');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马里', '马里共和国', 'Mali');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马耳他', '马耳他共和国', 'Malta');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马恩岛（英国）', '马恩岛', 'Isle of Man');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马绍尔群岛', '马绍尔群岛共和国', 'Marshall Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '毛里塔尼亚', '毛里塔尼亚伊斯兰共和国', 'Mauritania');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '毛里求斯', '毛里求斯共和国', 'Mauritius');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '马约特（法国）', '马约特', 'Mayotte');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '墨西哥', '墨西哥合众国', 'Mexico');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '密克罗尼西亚联邦', '密克罗尼西亚联邦', 'Micronesia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '摩尔多瓦', '摩尔多瓦共和国', 'Moldova');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '摩纳哥', '摩纳哥公国', 'Monaco');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '蒙古国', '蒙古国', 'Mongolia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '黑山', '黑山', 'Montenegro');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '蒙特塞拉特岛（英国）', '蒙特塞拉特', 'Montserrat');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '摩洛哥', '摩洛哥王国', 'Morocco');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '莫桑比克', '莫桑比克共和国', 'Mozambique');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '缅甸', '缅甸联邦共和国', 'Myanmar');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '纳戈尔诺-卡拉巴赫', '纳戈尔诺-卡拉巴赫共和国', 'Nagorno-Karabakh');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '纳米比亚', '纳米比亚共和国', 'Namibia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '瑙鲁', '瑙鲁共和国', 'Nauru');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '尼泊尔', '尼泊尔联邦民主共和国', 'Nepal');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '荷兰', '荷兰王国', 'Netherlands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '新喀里多尼亚（法国）', '新喀里多尼亚', 'New Caledonia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '新西兰', '新西兰', 'New Zealand');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '尼加拉瓜', '尼加拉瓜共和国', 'Nicaragua');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '尼日尔', '尼日尔共和国', 'Niger');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '尼日利亚', '尼日利亚联邦共和国', 'Nigeria');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '纽埃（新西兰）', '纽埃', 'Niue');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '诺福克岛（澳大利亚）', '诺福克岛', 'Norfolk Island');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '北塞浦路斯', '北塞浦路斯土耳其共和国', 'Northern Cyprus');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '北马里亚纳群岛（美国）', '北马里亚纳群岛邦', 'Northern Mariana Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '挪威', '挪威王国', 'Norway');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿曼', '阿曼苏丹国', 'Oman');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴基斯坦', '巴基斯坦伊斯兰共和国', 'Pakistan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '帕劳', '帕劳共和国', 'Palau');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴勒斯坦', '巴勒斯坦国', 'Palestine');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴拿马', '巴拿马共和国', 'Panama');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴布亚新几内亚', '巴布亚新几内亚独立国', 'Papua New Guinea');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '巴拉圭', '巴拉圭共和国', 'Paraguay');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '朝鲜', '朝鲜民主主义人民共和国', 'People\'s Republic of Korea');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '秘鲁', '秘鲁共和国', 'Peru');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '菲律宾', '菲律宾共和国', 'Philippines');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '皮特凯恩群岛（英国）', '皮特开恩群岛', 'Pitcairn Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '波兰', '波兰共和国', 'Poland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '葡萄牙', '葡萄牙共和国', 'Portugal');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '德涅斯特河左岸', '德涅斯特河沿岸摩尔达维亚共和国', 'Pridnestrovie');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '波多黎各（美国）', '波多黎各自由邦', 'Puerto Rico');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '卡塔尔', '卡塔尔国', 'Qatar');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '留尼汪（法国）', '留尼汪', 'Réunion');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '罗马尼亚', '罗马尼亚', 'Romania');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '俄罗斯', '俄罗斯联邦', 'Russia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '卢旺达', '卢旺达共和国', 'Rwanda');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣赫勒拿岛（英国）', '圣赫勒拿', 'Saint Helena');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣基茨和尼维斯', '圣基茨和尼维斯联邦', 'Saint Christopher and Nevis');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣卢西亚', '圣卢西亚', 'Saint Lucia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣皮埃尔和密克隆群岛（法国）', '圣皮埃尔和密克隆群岛', 'Saint Pierre and Miquelon');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣文森特和格林纳丁斯', '圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '萨摩亚', '萨摩亚独立国', 'Samoa');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣马利诺', '圣马力诺共和国', 'San Marino');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '圣多美和普林西比', '圣多美和普林西比民主共和国', 'São Tomé and Príncipe');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '沙特阿拉伯', '沙特阿拉伯王国', 'Saudi Arabia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塞内加尔', '塞内加尔共和国', 'Senegal');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塞尔维亚', '塞尔维亚共和国', 'Serbia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塞舌尔', '塞舌尔共和国', 'Seychelles');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塞拉利昂', '塞拉利昂共和国', 'Sierra Leone');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '新加坡', '新加坡共和国', 'Singapore');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '荷属圣马丁（荷兰）', '圣马丁', 'Sint Maarten');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斯洛伐克', '斯洛伐克共和国', 'Slovakia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斯洛文尼亚', '斯洛文尼亚共和国', 'Slovenia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '所罗门群岛', '所罗门群岛', 'Solomon Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '索马里', '索马里联邦共和国', 'Somali');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '索马里兰', '索马里兰共和国', 'Somaliland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '南非', '南非共和国', 'South Africa');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '南奥塞梯', '南奥塞梯共和国', 'South Ossetia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '南苏丹', '南苏丹共和国', 'South Sudan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '西班牙', '西班牙王国', 'Spain');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斯里兰卡', '斯里兰卡民主社会主义共和国', 'Sri Lanka');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '苏丹', '苏丹共和国', 'Sudan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '苏里南', '苏里南共和国', 'Suriname');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斯瓦尔巴群岛（挪威）', '斯瓦尔巴群岛', 'Svalbard');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '斯威士兰', '斯威士兰王国', 'Swaziland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '瑞典', '瑞典王国', 'Sweden');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '瑞士', '瑞士联邦', 'Switzerland');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '叙利亚', '阿拉伯叙利亚共和国', 'Syria');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '台湾', '中华民国（台湾）', 'Taiwan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '塔吉克斯坦', '塔吉克斯坦共和国', 'Tajikistan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '坦桑尼亚', '坦桑尼亚联合共和国', 'Tanzania');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '泰国', '泰王国', 'Thailand');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '东帝汶', '东帝汶民主共和国', 'Timor-Leste');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '多哥', '多哥共和国', 'Togo');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '托克劳（新西兰）', '托克劳', 'Tokelau');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '汤加', '汤加王国', 'Tonga');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '特立尼达和多巴哥', '特立尼达和多巴哥共和国', 'Trinidad and Tobago');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '突尼斯', '突尼斯共和国', 'Tunisia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '土耳其', '土耳其共和国', 'Turkey');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '土库曼斯坦', '土库曼斯坦', 'Turkmenistan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '特克斯和凯科斯群岛（英国）', '特克斯与凯科斯群岛', 'Turks and Caicos Islands');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '图瓦卢', '图瓦卢', 'Tuvalu');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '乌干达', '乌干达共和国', 'Uganda');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '乌克兰', '乌克兰', 'Ukraine');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '阿联酋', '阿拉伯联合酋长国', 'United Arab Emirates');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '英国', '大不列颠及北爱尔兰联合王国', 'United Kingdom');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '美国', '美利坚合众国', 'United States');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '乌拉圭', '乌拉圭东岸共和国', 'Uruguay');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '乌兹别克斯坦', '乌兹别克斯坦共和国', 'Uzbekistan');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '瓦努阿图', '瓦努阿图共和国', 'Vanuatu');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '梵蒂冈', '梵蒂冈城国', 'The Holy See（Vatican City）');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '委内瑞拉', '委内瑞拉玻利瓦尔共和国', 'Venezuela');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '越南', '越南社会主义共和国', 'Vietnam');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '英属维尔京群岛（英国）', '英属维京群岛', 'Virgin Islands, British');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '美属维尔京群岛（美国）', '美属维京群岛', 'Virgin Islands, United States');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '瓦利斯和富图纳群岛（法国）', '瓦利斯和富图纳群岛', 'Wallis and Futuna');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '西撒哈拉', '阿拉伯撒哈拉民主共和国', 'Western Sahara');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '也门', '也门共和国', 'Yemen');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '赞比亚', '赞比亚共和国', 'Zambia');
INSERT INTO `dbhx_tianjin`.`t_country` (`sh_name`,`zh_name`,`en_name`) VALUES ( '津巴布韦', '津巴布韦共和国', 'Zimbabwe');