package com.jusfoun.service;
 
import com.jusfoun.entity.TTest;
import com.jusfoun.common.base.service.BaseIdableService;

/**
* generated by ServiceGeneratorPlugin.java
*/
public interface TTestService extends BaseIdableService<TTest>{
 
}
