package com.jusfoun.web.controller;
 
import com.jusfoun.entity.TTest;
import com.jusfoun.service.TTestService;
import com.jusfoun.common.base.service.BaseService;
import com.jusfoun.common.base.service.BaseIdableService;
import com.jusfoun.common.base.controller.BaseIdableController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
 
/**
*  generated by ControllerGeneratorPlugin.java plugin
*/
@RestController
@RequestMapping("/api/tTest")
public class TTestController implements BaseIdableController<TTest,Long>  {
 
	@Autowired
	private TTestService tTestService;
	
	@Override
	public BaseService<TTest> getBaseService() {
		return tTestService;
	}
	
	@Override
	public BaseIdableService<TTest> getBaseIdableService() {
		return tTestService;
	}
	
}