package ${targetPackage};
 
import ${entityPackage}.${EntityName};
import ${injectPackage}.${EntityName}Service;
import com.jusfoun.common.base.service.BaseService;
import com.jusfoun.common.base.service.BaseIdableService;
import com.jusfoun.common.base.controller.BaseIdableController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
 
/**
*  generated by ControllerGeneratorPlugin.java plugin
*/
@RestController
@RequestMapping("/api/${entityName}")
public class ${EntityName}Controller implements BaseIdableController<${EntityName},Long>  {
 
	@Autowired
	private ${EntityName}Service ${entityName}Service;
	
	@Override
	public BaseService<${EntityName}> getBaseService() {
		return ${entityName}Service;;
	}
	
	@Override
	public BaseIdableService<${EntityName}> getBaseIdableService() {
		return ${entityName}Service;;
	}
	
}