package ${targetPackage};
 
import ${entityPackage}.${EntityName};
import ${injectPackage}.${EntityName}Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
 
/**
*  generated by ControllerGeneratorPlugin.java plugin
*/
@RestController
@RequestMapping("/api/${entityName}")
public class ${EntityName}Controller {
 
	@Autowired
	private ${EntityName}Service ${entityName}Service;
	
}