package ${targetPackage}.impl;
 
import ${entityPackage}.${EntityName};
import ${injectPackage}.${EntityName}Mapper;
import ${targetPackage}.${EntityName}Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
 
/**
*  generated by ServiceGeneratorPlugin.java
*/
@Service
public class ${EntityName}ServiceImpl implements ${EntityName}Service{
	
	@Autowired
	private ${EntityName}Mapper ${entityName}Mapper;
 
}
