package ${targetPackage};
 
import ${entityPackage}.${EntityName};
import com.jusfoun.common.base.service.BaseIdableService;

/**
* generated by ServiceGeneratorPlugin.java
*/
public interface ${EntityName}Service extends BaseIdableService<${EntityName}>{
 
}
