spring:
  application:
    name: sbm-demo
  profiles:
    active:
     - @profileActive@
  cache:
    type: redis
    cache-names:
    - tempCache
    - customCache
    - persistentCache
    - securityCache
#    ehcache:
#      config: classpath:extends/cache/ehcache/ehcache.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: true
  resources:
    add-mappings: false
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:${system.file.upload.root}
  http:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 10MB
      resolve-lazily: true
      file-size-threshold: 0
    converters:
      preferred-json-mapper: jackson
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  pid:
    file: target/${spring.application.name}.pid
    fail-on-write-error: true

security:
#  enable-csrf: false
#  ignored:
#  - /**
#  headers:
#    cache: true
#    xss: true
#  basic:
#    authorize-mode: authenticated
#    enabled: true
#    path:
#    - /**
#    realm: Spring
   jwt:
    accessTokenExpIn: 60000
    refreshTokenExpIn: 72000
    tokenIssuer: tjhx.9cfcf.com
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
   custom:
    ignoredStaticResources: 
      - /
      - /files/**
      - /static/**
      - /app/static/**
      - /bigData/static/**
      - /test/**
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.ico
      - /webjars/**
      - /swagger-ui.html**
    ignoredGetResources: 
      - /qcode/showCode
      - /country/export
      - /swagger-resources/**
      - /v2/**
    ignoredPostResources:
      - /country/export
      - /swagger-resources/**
      - /test/**
mapper:
    not-empty: false
    identity: MYSQL
    style: camelhumpanduppercase
    enable-method-annotation: true
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
server:
  servlet:
    context-path: /sbm-demo
    application-display-name: /SBM-DEMO
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
    min-response-size: 2048
  tomcat:
    basedir: target/tomcat
    accesslog:
      enabled: true
      directory: logs
    max-threads: 200
    uri-encoding: UTF-8
  error:
    path: /error
logging:
  session:
    timeout: 60
    
templates:
  dir: /extends/templets/
  countries: countries.ftl
  
jasypt:
  encryptor:
    password: xm8EV6Hy5RMFK4EEACIDAwQus
       