spring:
  datasource:
    hikari:
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sbm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: ENC(3PVCf6aMsTLbiRP04tKhIw==)
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sbm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: ENC(3PVCf6aMsTLbiRP04tKhIw==)
  cache:
    type: redis
    cache-names:
    - tempCache
    - customCache
    - persistentCache
    - securityCache
    redis:
      time-to-live:
        seconds: 3600
  redis:
    host: 127.0.0.1
    port: 6379
    password: 20cb49ac2ab948028d1a80225f44b043
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1s
server:
  port: 8080
swagger:
  enable: false
system:
  init:
    enable: false
    username: admin
    password: 123456
    sysPrivssFile: classpath:extends/init/SysPrivss.xml
    clientDetailsFile: classpath:extends/init/ClientDetails.xml
  file:
    upload:
      root: D:/wfny/upload
      rootDir: /atts
      separator: ;
      suffix: jpg,png,jpeg,tiff,gif,bmp,flv,mp4,txt,doc,docx,xls,xlsx,pdf,zip,rar
  urls:
    baseUrl: http://192.168.21.31:${server.port}/
    baseLoginUrl: ${system.constants.baseUrl}/app/index.html%s/baseLogin?id=%s
    inputOriginUrl: ${system.constants.baseUrl}/app/index.html%s/inputOrigin?id=%s