spring:
  datasource:
    hikari:
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sbm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: ENC(3PVCf6aMsTLbiRP04tKhIw==)
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sbm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
        username: root
        password: ENC(3PVCf6aMsTLbiRP04tKhIw==)
  cache:
    type: ehcache
    cache-names:
    - tempCache
    - customCache
    - persistentCache
    - securityCache
    ehcache:
      config: classpath:extends/cache/ehcache/ehcache.xml
server:
  port: 8080
swagger:
  enable: true
system:
  init:
    enable: false
    username: admin
    password: 123456
    sysPrivssFile: classpath:extends/init/SysPrivss.xml
    clientDetailsFile: classpath:extends/init/ClientDetails.xml
  file:
    upload:
      root: D:/wfny/upload
      rootDir: /atts
      separator: ;
      suffix: jpg,png,jpeg,tiff,gif,bmp,flv,mp4,txt,doc,docx,xls,xlsx,pdf,zip,rar
  urls:
    baseUrl: http://tjhx.9cfcf.com:${server.port}/
    baseLoginUrl: ${system.constants.baseUrl}/app/index.html%s/baseLogin?id=%s
    inputOriginUrl: ${system.constants.baseUrl}/app/index.html%s/inputOrigin?id=%s