package com.jusfoun.service.impl;
 
import com.jusfoun.entity.TTest;
import com.jusfoun.mapper.ds1.TTestMapper;
import com.jusfoun.service.TTestService;
import com.jusfoun.common.mybatis.mapper.MyBaseMapper;
import com.jusfoun.common.mybatis.mapper.MyIdableMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
 
/**
*  generated by ServiceGeneratorPlugin.java
*/
@Service
public class TTestServiceImpl implements TTestService{
	
	@Autowired
	private TTestMapper tTestMapper;
	
	@Override
	public MyBaseMapper<TTest> getMyBaseMapper() {
		return tTestMapper;
	}
	
	@Override
	public MyIdableMapper<TTest> getMyIdableMapper() {
		return tTestMapper;
	}
 
}
