spring:
  datasource:
    hikari:
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ssm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
        username: root
        password: root
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ssm-demo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
        username: root
        password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 20cb49ac2ab948028d1a80225f44b043
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
server:
  port: 8080
system:
  user:
    init-password: 123456
  sysModule:
    init-file: classpath:SysModule.xml
  enterprise:
    init-file: classpath:Enterprise.xml
  clientDetails:
    init-file: classpath:ClientDetails.xml
  file:
    upload:
      root: D:/tianjinhexie/upload
      rootDir: /files
      separator: ;
      suffix: jpg,png,jpeg,tiff,flv,mp4
  constants:
    baseUrl: http://tjhx.9cfcf.com/aobo
    baseLoginUrl: ${system.constants.baseUrl}/app/index.html%s/baseLogin?id=%s
    inputOriginUrl: ${system.constants.baseUrl}/app/index.html%s/inputOrigin?id=%s
  modbus:
    ip: 60.15.167.154
    port: 3001
    slaveId: 1
    start: 3
    readLenth: 40