spring:
  datasource:
    ds0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dbhx_tianjin?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true
      username: root
      password: root
      maxActive: 80     #最大活动连接
      initialSize: 10   #初始化连接
      maxIdle: 60       #最大空闲连接
      minIdle: 10       #最小空闲连接
      maxWait: 3000     #从池中取连接的最大等待时间，单位ms
      validationQuery: SELECT 1  #验证使用的SQL语句
      testWhileIdle: true      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testOnBorrow: false      #拿出连接时不要测试，否则很影响性能
      timeBetweenEvictionRunsMillis: 30000  #每30秒运行一次空闲连接回收器
      minEvictableIdleTimeMillis: 1800000   #池中的连接空闲30分钟后被回收
      numTestsPerEvictionRun: 3 #在每次空闲连接回收器线程(如果有)运行时检查的连接数量
server:
  port: 8080
system:
  user:
    init-password: 123456
  sysModule:
    init-file: classpath:SysModule.xml
  enterprise:
    init-file: classpath:Enterprise.xml
  clientDetails:
    init-file: classpath:ClientDetails.xml
  file:
    upload:
      root: D:/tianjinhexie/upload
      rootDir: /files
      separator: ;
      suffix: jpg,png,jpeg,tiff,flv,mp4
  constants:
    baseUrl: http://192.168.21.31:8080/aobo
    baseLoginUrl: ${system.constants.baseUrl}/app/index.html%s/baseLogin?id=%s
    inputOriginUrl: ${system.constants.baseUrl}/app/index.html%s/inputOrigin?id=%s
  modbus:
    ip: 60.15.167.154
    port: 3001
    slaveId: 1
    start: 3
    readLenth: 40
  price:
     marketUrl: http://api.imjuxin.com/sql/dianshang_goods_price_%s_%02d.sql.gz
     eCommerceUrl: http://api.imjuxin.com/sql/pifa_goods_price_%s_%02d.sql.gz
     forecastUrl: http://202.106.10.250:5013/predict/fx_price_forecast_%s_%02d.sql.gz
     amHour: 10
     pmHour: 18
